# Generated by Django 4.1.1 on 2022-09-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_rename_book_quote_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='source',
            new_name='book',
        ),
    ]
