# Generated by Django 4.1.1 on 2022-09-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_rename_source_quote_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='text',
            new_name='quote',
        ),
    ]
