# Generated by Django 4.1.1 on 2022-09-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_rename_text_quote_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='category',
            field=models.ManyToManyField(related_name='quotes', to='quotes.quotecategory'),
        ),
    ]
