# Generated by Django 4.1.1 on 2022-09-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_quotecategory_quote_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotecategory',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
