# Generated by Django 4.1.1 on 2022-09-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_alter_quotecategory_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuoteCategory',
            new_name='Category',
        ),
    ]
