# Generated by Django 4.1.1 on 2022-09-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_rename_quotecategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='category',
            new_name='categories',
        ),
    ]
