# Generated by Django 4.1.1 on 2022-09-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_rename_category_quote_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
